server.port=${PORT:8081}
spring.application.name=profile
# Tell Spring to use H2 locally
spring.datasource.url=jdbc:h2:mem:profiledb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Automatically create the database tables based on our Java code!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

# Enable the H2 web console so we can see our database in the browser
spring.h2.console.enabled=true
spring.security.oauth2.client.registration.github.client-id=Ov23lihfaiVSUib1dWhS
spring.security.oauth2.client.registration.github.client-secret=543ef63eee2e1251479c11c2ee686cca5ea48543

jwt.secret=a_very_long_and_very_secure_random_string_that_is_at_least_32_chars

admin.github.ids=37679347

